model_name: "flux-dev"
data_config:
  train_batch_size: 2
  num_workers: 4
  img_size: 128
  img_dir: ./word_dataset/HUST-OBC
  font_path: ./unifont
  use_undeciphered: false
report_to: tensorboard
train_batch_size: 2
output_dir: ckpts/oracle_v3.1/
max_train_steps: 1000000
learning_rate: 5e-6
lr_scheduler: constant
lr_warmup_steps: 10
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 0.01
adam_epsilon: 1e-8
max_grad_norm: 1.0
logging_dir: logs
mixed_precision: "bf16"
checkpointing_steps: 20000
checkpoints_total_limit: 10
tracker_project_name: oracle
resume_from_checkpoint: latest
gradient_accumulation_steps: 1
disable_sampling: false
sample_every: 20000 # sample every this many steps
sample_width: 128
sample_height: 128
sample_steps: 25
sample_prompts:
 - "ancient Chinese oracle bone script carved into a cracked turtle plastron and ox scapula"
 - "ancient Chinese oracle bone script carved into a cracked turtle plastron and ox scapula"
 - "ancient Chinese oracle bone script carved into a cracked turtle plastron and ox scapula"
 - "ancient Chinese oracle bone script carved into a cracked turtle plastron and ox scapula"
 - "ancient Chinese oracle bone script carved into a cracked turtle plastron and ox scapula"
 - "ancient Chinese oracle bone script carved into a cracked turtle plastron and ox scapula"
 - "ancient Chinese oracle bone script carved into a cracked turtle plastron and ox scapula"
 - "ancient Chinese oracle bone script carved into a cracked turtle plastron and ox scapula"
