model_name: "flux-dev"
debug_mode: false
data_config:
  train_batch_size: 1
  num_workers: 4
  img_size: 128
  img_dir: ./word_dataset/finalpage
  synth_prob: 0.3
  data_aug: true
  author_descriptions: ./word_dataset/calligraphy_styles_en.json
  font_descriptions: ./word_dataset/chirography.json
  tokenizer_path: "/data/user/txu647/.cache/InternVL3-1B"
report_to: tensorboard
train_batch_size: 1
output_dir: ckpts/general_v4/  # fix noise schedule
ref_latent_path: ./ttf_chars_128_latents.pt
max_train_steps: 1000000
learning_rate: 1e-6
lr_scheduler: constant
lr_warmup_steps: 10
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 0.01
adam_epsilon: 1e-8
max_grad_norm: 1.0
logging_dir: logs
mixed_precision: "bf16"
checkpointing_steps: 20000
checkpoints_total_limit: 10
tracker_project_name: unicalli
test_data_path: test_data/debug
resume_from_checkpoint: latest
gradient_accumulation_steps: 1
disable_sampling: false
sample_every: 10000 # sample every this many steps
sample_width: 128
sample_height: 640
sample_steps: 39
sample_prompts:
 - "Traditional Chinese calligraphy works, background: black, font: cao, coherent and smooth strokes, sparse and dense structure, and more free structure. Sometimes up, down, left and right compress or stretch to match the strokes. author: Sun Guoting (646–691), a Tang dynasty calligrapher, is best known for his 'Treatise on Calligraphy' (Shu Pu), an influential theoretical and artistic work written in running script, blending philosophical insight with masterful technique."
 - "Traditional Chinese calligraphy works, background: black, font: kai, symmetrical structure, stable center of gravity, rigorous layout of the frame, clear gaps between strokes, easy to identify the shape of the characters. author: Zhang Jizhi (1186–1266), a Southern Song calligrapher, excelled in regular and running scripts. His works were upright, powerful, and faithful to Tang models, often compared to Yan Zhenqing."
 - "Traditional Chinese calligraphy works, background: black, font: xing, a calligraphic style that blends structure and freedom, featuring fluid strokes, moderate simplification, and expressive rhythm while preserving readability. author: Mi Fu (1051–1107), a Northern Song calligrapher, painter, and connoisseur, was famous for his running and cursive scripts, characterized by elegance, speed, and rhythm."
 - "Traditional Chinese calligraphy works, background: black, font: kai, symmetrical structure, stable center of gravity, rigorous layout of the frame, clear gaps between strokes, easy to identify the shape of the characters. author: Yan Zhenqing (709–785), a Tang dynasty calligrapher and loyal official, was a master of regular script, creating a robust, upright style that emphasized moral integrity. Works like 'Yan Qinli Stele' remain exemplary."
 - "Traditional Chinese calligraphy works, background: black, font: xing, a calligraphic style that blends structure and freedom, featuring fluid strokes, moderate simplification, and expressive rhythm while preserving readability. author: Huang Tingjian (1045–1105), a Northern Song poet and calligrapher, was a master of running script, developing a distinctive, elongated style influenced by Su Shi and ancient models."
 - "Traditional Chinese calligraphy works, background: black, font: kai, symmetrical structure, stable center of gravity, rigorous layout of the frame, clear gaps between strokes, easy to identify the shape of the characters. author: Zhao Ji (1082–1135), Emperor Huizong of the Northern Song, created the slender-gold script (shoujin ti), a distinctive, elegant style marked by fine lines and angular turns."