model_name: "flux-dev"
data_config:
  train_batch_size: 2
  num_workers: 4
  img_size: 256
  img_dir: ./word_dataset/finalpage
  required_chars: 5
report_to: tensorboard
train_batch_size: 2
output_dir: ckpts/ckpts-column-cnt-chars5-newcap2-w.synth/
max_train_steps: 200000
learning_rate: 2e-5
lr_scheduler: constant
lr_warmup_steps: 10
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 0.01
adam_epsilon: 1e-8
max_grad_norm: 1.0
logging_dir: logs
mixed_precision: "bf16"
checkpointing_steps: 20000
checkpoints_total_limit: 14
tracker_project_name: cn_word_training
resume_from_checkpoint: latest
gradient_accumulation_steps: 2
