model_name: "flux-dev"
data_config:
  train_batch_size: 2
  num_workers: 4
  img_size: 128
  img_dir: ./word_dataset/finalpage
  synth_prob: 0.2
  data_aug: true
report_to: wandb
train_batch_size: 2
output_dir: ckpts/generation_v2/
max_train_steps: 500000
learning_rate: 5e-6
lr_scheduler: constant
lr_warmup_steps: 10
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 0.01
adam_epsilon: 1e-8
max_grad_norm: 1.0
logging_dir: logs
mixed_precision: "bf16"
checkpointing_steps: 5000
checkpoints_total_limit: 10
tracker_project_name: finetune_test
resume_from_checkpoint: latest
gradient_accumulation_steps: 1
disable_sampling: false
sample_every: 5000 # sample every this many steps
sample_width: 128
sample_height: 640
sample_steps: 25
sample_prompts:
 - "Traditional Chinese calligraphy works, font: line, background: black, author: Wang Xizhi, the saint of calligraphy in the Eastern Jin Dynasty, each style is exquisite.The brushwork is magical and elegant. It is known as the highest peak in the history of calligraphy and has influenced all the time."
 - "Traditional Chinese calligraphy works, font: line, background: black, author: Wang Xizhi, the saint of calligraphy in the Eastern Jin Dynasty, each style is exquisite.The brushwork is magical and elegant. It is known as the highest peak in the history of calligraphy and has influenced all the time."
 - "Traditional Chinese calligraphy works, font: line, background: white, author: Wang Xizhi, the saint of calligraphy in the Eastern Jin Dynasty, each style is exquisite.The brushwork is magical and elegant. It is known as the highest peak in the history of calligraphy and has influenced all the time."
 - "Traditional Chinese calligraphy works, font: line, background: white, author: Wang Xizhi, the saint of calligraphy in the Eastern Jin Dynasty, each style is exquisite.The brushwork is magical and elegant. It is known as the highest peak in the history of calligraphy and has influenced all the time."
 - "Synthetic calligraphy data, background: white, font: grass, features: coherent and smooth strokes, sparse and dense structure, and more free structure. Sometimes up, down, left and right compress or stretch to match the strokes"
 - "Synthetic calligraphy data, background: white, font: regular, features: symmetrical structure, stable center of gravity, rigorous layout of the frame, clear gaps between strokes, easy to identify the shape of the characters"
 - "Synthetic calligraphy data, background: black, font: regular, features: symmetrical structure, stable center of gravity, rigorous layout of the frame, clear gaps between strokes, easy to identify the shape of the characters"
 - "Synthetic calligraphy data, background: black, font: grass, features: coherent and smooth strokes, sparse and dense structure, and more free structure. Sometimes up, down, left and right compress or stretch to match the strokes"
